name = "TensorFactors"
uuid = "dbfff67a-e1b2-4b37-8c6f-9fb5ab74d5d7"
authors = ["dishangti <16698219+dishangti@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
